/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentRegistry {
      
    export type AgentProfileStruct = {owner: AddressLike, metadataURI: string, registeredAt: BigNumberish, reputation: BigNumberish, totalEarned: BigNumberish, tasksCompleted: BigNumberish, stakedAmount: BigNumberish, isActive: boolean}

    export type AgentProfileStructOutput = [owner: string, metadataURI: string, registeredAt: bigint, reputation: bigint, totalEarned: bigint, tasksCompleted: bigint, stakedAmount: bigint, isActive: boolean] & {owner: string, metadataURI: string, registeredAt: bigint, reputation: bigint, totalEarned: bigint, tasksCompleted: bigint, stakedAmount: bigint, isActive: boolean }
  
    }

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addStake" | "agentList" | "agents" | "deactivate" | "getAgent" | "getAgentCount" | "getAgentList" | "getReputation" | "getReputationTier" | "getReputationTierByValue" | "isRegistered" | "minimumStake" | "owner" | "recordTaskCompletion" | "registerAgent" | "registrationCount" | "rektToken" | "renounceOwnership" | "setMinimumStake" | "totalStaked" | "transferOwnership" | "updateMetadata" | "updateReputation" | "withdrawStake"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentDeactivated" | "AgentRegistered" | "AgentUpdated" | "MinimumStakeUpdated" | "OwnershipTransferred" | "ReputationUpdated" | "StakeAdded" | "StakeWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'addStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'agentList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agents', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deactivate', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAgentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgentList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReputationTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReputationTierByValue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'minimumStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordTaskCompletion', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [string]): string;
encodeFunctionData(functionFragment: 'registrationCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'rektToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMinimumStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalStaked', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMetadata', values: [string]): string;
encodeFunctionData(functionFragment: 'updateReputation', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawStake', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputationTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputationTierByValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordTaskCompletion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rektToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinimumStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawStake', data: BytesLike): Result;
  }

  
    export namespace AgentDeactivatedEvent {
      export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, timestamp: bigint];
      export interface OutputObject {agent: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agent: AddressLike, metadataURI: string, stake: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, metadataURI: string, stake: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, metadataURI: string, stake: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [agent: AddressLike, newMetadataURI: string, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, newMetadataURI: string, timestamp: bigint];
      export interface OutputObject {agent: string, newMetadataURI: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinimumStakeUpdatedEvent {
      export type InputTuple = [oldMinimum: BigNumberish, newMinimum: BigNumberish];
      export type OutputTuple = [oldMinimum: bigint, newMinimum: bigint];
      export interface OutputObject {oldMinimum: bigint, newMinimum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [agent: AddressLike, oldReputation: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [agent: string, oldReputation: bigint, newReputation: bigint];
      export interface OutputObject {agent: string, oldReputation: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeAddedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, totalStake: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, totalStake: bigint];
      export interface OutputObject {agent: string, amount: bigint, totalStake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeWithdrawnEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addStake: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    agentList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agents: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {owner: string, metadataURI: string, registeredAt: bigint, reputation: bigint, totalEarned: bigint, tasksCompleted: bigint, stakedAmount: bigint, isActive: boolean }],
      'view'
    >
    

    
    deactivate: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [wallet: AddressLike, ],
      [AgentRegistry.AgentProfileStructOutput],
      'view'
    >
    

    
    getAgentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAgentList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getReputation: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getReputationTier: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getReputationTierByValue: TypedContractMethod<
      [reputation: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minimumStake: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordTaskCompletion: TypedContractMethod<
      [agent: AddressLike, rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerAgent: TypedContractMethod<
      [metadataURI: string, ],
      [void],
      'payable'
    >
    

    
    registrationCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rektToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setMinimumStake: TypedContractMethod<
      [newMinimum: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalStaked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMetadata: TypedContractMethod<
      [newMetadataURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateReputation: TypedContractMethod<
      [agent: AddressLike, newReputation: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawStake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addStake'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'agentList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {owner: string, metadataURI: string, registeredAt: bigint, reputation: bigint, totalEarned: bigint, tasksCompleted: bigint, stakedAmount: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'deactivate'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [wallet: AddressLike, ],
      [AgentRegistry.AgentProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getReputationTier'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReputationTierByValue'): TypedContractMethod<
      [reputation: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minimumStake'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordTaskCompletion'): TypedContractMethod<
      [agent: AddressLike, rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [metadataURI: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'registrationCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rektToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinimumStake'): TypedContractMethod<
      [newMinimum: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalStaked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMetadata'): TypedContractMethod<
      [newMetadataURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateReputation'): TypedContractMethod<
      [agent: AddressLike, newReputation: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawStake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentDeactivated'): TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
getEvent(key: 'MinimumStakeUpdated'): TypedContractEvent<MinimumStakeUpdatedEvent.InputTuple, MinimumStakeUpdatedEvent.OutputTuple, MinimumStakeUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
getEvent(key: 'StakeAdded'): TypedContractEvent<StakeAddedEvent.InputTuple, StakeAddedEvent.OutputTuple, StakeAddedEvent.OutputObject>;
getEvent(key: 'StakeWithdrawn'): TypedContractEvent<StakeWithdrawnEvent.InputTuple, StakeWithdrawnEvent.OutputTuple, StakeWithdrawnEvent.OutputObject>;

    filters: {
      
      'AgentDeactivated(address,uint256)': TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
      AgentDeactivated: TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
    

      'AgentRegistered(address,string,uint256,uint256)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AgentUpdated(address,string,uint256)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    

      'MinimumStakeUpdated(uint256,uint256)': TypedContractEvent<MinimumStakeUpdatedEvent.InputTuple, MinimumStakeUpdatedEvent.OutputTuple, MinimumStakeUpdatedEvent.OutputObject>;
      MinimumStakeUpdated: TypedContractEvent<MinimumStakeUpdatedEvent.InputTuple, MinimumStakeUpdatedEvent.OutputTuple, MinimumStakeUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReputationUpdated(address,uint256,uint256)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    

      'StakeAdded(address,uint256,uint256)': TypedContractEvent<StakeAddedEvent.InputTuple, StakeAddedEvent.OutputTuple, StakeAddedEvent.OutputObject>;
      StakeAdded: TypedContractEvent<StakeAddedEvent.InputTuple, StakeAddedEvent.OutputTuple, StakeAddedEvent.OutputObject>;
    

      'StakeWithdrawn(address,uint256,uint256)': TypedContractEvent<StakeWithdrawnEvent.InputTuple, StakeWithdrawnEvent.OutputTuple, StakeWithdrawnEvent.OutputObject>;
      StakeWithdrawn: TypedContractEvent<StakeWithdrawnEvent.InputTuple, StakeWithdrawnEvent.OutputTuple, StakeWithdrawnEvent.OutputObject>;
    
    };
  }