/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentStaking {
      
    export type StakeInfoStruct = {amount: BigNumberish, stakedAt: BigNumberish, cooldownStart: BigNumberish, inCooldown: boolean}

    export type StakeInfoStructOutput = [amount: bigint, stakedAt: bigint, cooldownStart: bigint, inCooldown: boolean] & {amount: bigint, stakedAt: bigint, cooldownStart: bigint, inCooldown: boolean }
  
    }

  export interface AgentStakingInterface extends Interface {
    getFunction(nameOrSignature: "COOLDOWN_PERIOD" | "addStake" | "canUnstake" | "cancelUnstake" | "cooldownRemaining" | "getStake" | "getStakeInfo" | "getStakeMultiplier" | "initiateUnstake" | "minStake" | "owner" | "rektToken" | "renounceOwnership" | "setMinStake" | "slash" | "stake" | "stakes" | "totalStaked" | "transferOwnership" | "unstake" | "withdrawSlashed"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MinStakeUpdated" | "OwnershipTransferred" | "StakeSlashed" | "Staked" | "UnstakeInitiated" | "Unstaked"): EventFragment;

    encodeFunctionData(functionFragment: 'COOLDOWN_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'addStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'canUnstake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelUnstake', values?: undefined): string;
encodeFunctionData(functionFragment: 'cooldownRemaining', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStakeInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStakeMultiplier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initiateUnstake', values?: undefined): string;
encodeFunctionData(functionFragment: 'minStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'rektToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMinStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'slash', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalStaked', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unstake', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawSlashed', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'COOLDOWN_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cooldownRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakeInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakeMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rektToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawSlashed', data: BytesLike): Result;
  }

  
    export namespace MinStakeUpdatedEvent {
      export type InputTuple = [newMin: BigNumberish];
      export type OutputTuple = [newMin: bigint];
      export interface OutputObject {newMin: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeSlashedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [agent: string, amount: bigint, reason: string];
      export interface OutputObject {agent: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, totalStaked: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, totalStaked: bigint];
      export interface OutputObject {agent: string, amount: bigint, totalStaked: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeInitiatedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, cooldownEnd: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, cooldownEnd: bigint];
      export interface OutputObject {agent: string, amount: bigint, cooldownEnd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint];
      export interface OutputObject {agent: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentStaking extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentStaking;
    waitForDeployment(): Promise<this>;

    interface: AgentStakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COOLDOWN_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addStake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    canUnstake: TypedContractMethod<
      [agent: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    cancelUnstake: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    cooldownRemaining: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getStake: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getStakeInfo: TypedContractMethod<
      [agent: AddressLike, ],
      [AgentStaking.StakeInfoStructOutput],
      'view'
    >
    

    
    getStakeMultiplier: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    initiateUnstake: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    minStake: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rektToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setMinStake: TypedContractMethod<
      [_minStake: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    slash: TypedContractMethod<
      [agent: AddressLike, amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakes: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {amount: bigint, stakedAt: bigint, cooldownStart: bigint, inCooldown: boolean }],
      'view'
    >
    

    
    totalStaked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unstake: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawSlashed: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COOLDOWN_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addStake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'canUnstake'): TypedContractMethod<
      [agent: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'cancelUnstake'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cooldownRemaining'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStake'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStakeInfo'): TypedContractMethod<
      [agent: AddressLike, ],
      [AgentStaking.StakeInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStakeMultiplier'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initiateUnstake'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'minStake'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rektToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinStake'): TypedContractMethod<
      [_minStake: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slash'): TypedContractMethod<
      [agent: AddressLike, amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakes'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {amount: bigint, stakedAt: bigint, cooldownStart: bigint, inCooldown: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'totalStaked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawSlashed'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MinStakeUpdated'): TypedContractEvent<MinStakeUpdatedEvent.InputTuple, MinStakeUpdatedEvent.OutputTuple, MinStakeUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'StakeSlashed'): TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'UnstakeInitiated'): TypedContractEvent<UnstakeInitiatedEvent.InputTuple, UnstakeInitiatedEvent.OutputTuple, UnstakeInitiatedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;

    filters: {
      
      'MinStakeUpdated(uint256)': TypedContractEvent<MinStakeUpdatedEvent.InputTuple, MinStakeUpdatedEvent.OutputTuple, MinStakeUpdatedEvent.OutputObject>;
      MinStakeUpdated: TypedContractEvent<MinStakeUpdatedEvent.InputTuple, MinStakeUpdatedEvent.OutputTuple, MinStakeUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'StakeSlashed(address,uint256,string)': TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
      StakeSlashed: TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
    

      'Staked(address,uint256,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'UnstakeInitiated(address,uint256,uint256)': TypedContractEvent<UnstakeInitiatedEvent.InputTuple, UnstakeInitiatedEvent.OutputTuple, UnstakeInitiatedEvent.OutputObject>;
      UnstakeInitiated: TypedContractEvent<UnstakeInitiatedEvent.InputTuple, UnstakeInitiatedEvent.OutputTuple, UnstakeInitiatedEvent.OutputObject>;
    

      'Unstaked(address,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    
    };
  }