/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentGovernance {
      
    export type ProposalStruct = {id: BigNumberish, proposer: AddressLike, description: string, metadataURI: string, forVotes: BigNumberish, againstVotes: BigNumberish, startBlock: BigNumberish, endBlock: BigNumberish, executed: boolean, cancelled: boolean, callData: BytesLike, targetContract: AddressLike}

    export type ProposalStructOutput = [id: bigint, proposer: string, description: string, metadataURI: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, cancelled: boolean, callData: string, targetContract: string] & {id: bigint, proposer: string, description: string, metadataURI: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, cancelled: boolean, callData: string, targetContract: string }
  
    }

  export interface AgentGovernanceInterface extends Interface {
    getFunction(nameOrSignature: "cancelProposal" | "castVote" | "executeProposal" | "getProposal" | "getProposalState" | "getVotingPower" | "hasVoted" | "owner" | "proposalCount" | "proposalThreshold" | "proposals" | "propose" | "quorumPercent" | "renounceOwnership" | "setProposalThreshold" | "setQuorum" | "setStakingContract" | "setVotingPeriod" | "stakingContract" | "transferOwnership" | "voteChoice" | "votingPeriod"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ProposalCancelled" | "ProposalCreated" | "ProposalExecuted" | "QuorumUpdated" | "ThresholdUpdated" | "VoteCast" | "VotingPeriodUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'castVote', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposalState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVotingPower', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propose', values: [string, string, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'quorumPercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setProposalThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setQuorum', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setStakingContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setVotingPeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voteChoice', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'votingPeriod', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'cancelProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'castVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposalState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVotingPower', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propose', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorumPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProposalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuorum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStakingContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVotingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteChoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingPeriod', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCancelledEvent {
      export type InputTuple = [proposalId: BigNumberish];
      export type OutputTuple = [proposalId: bigint];
      export interface OutputObject {proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, proposer: AddressLike, description: string, startBlock: BigNumberish, endBlock: BigNumberish];
      export type OutputTuple = [proposalId: bigint, proposer: string, description: string, startBlock: bigint, endBlock: bigint];
      export interface OutputObject {proposalId: bigint, proposer: string, description: string, startBlock: bigint, endBlock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish];
      export type OutputTuple = [proposalId: bigint];
      export interface OutputObject {proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuorumUpdatedEvent {
      export type InputTuple = [newQuorum: BigNumberish];
      export type OutputTuple = [newQuorum: bigint];
      export interface OutputObject {newQuorum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdUpdatedEvent {
      export type InputTuple = [newThreshold: BigNumberish];
      export type OutputTuple = [newThreshold: bigint];
      export interface OutputObject {newThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [proposalId: BigNumberish, voter: AddressLike, support: boolean, weight: BigNumberish];
      export type OutputTuple = [proposalId: bigint, voter: string, support: boolean, weight: bigint];
      export interface OutputObject {proposalId: bigint, voter: string, support: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingPeriodUpdatedEvent {
      export type InputTuple = [newPeriod: BigNumberish];
      export type OutputTuple = [newPeriod: bigint];
      export interface OutputObject {newPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentGovernance extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentGovernance;
    waitForDeployment(): Promise<this>;

    interface: AgentGovernanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    castVote: TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [AgentGovernance.ProposalStructOutput],
      'view'
    >
    

    
    getProposalState: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getVotingPower: TypedContractMethod<
      [voter: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposalThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean, string, string] & {id: bigint, proposer: string, description: string, metadataURI: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, cancelled: boolean, callData: string, targetContract: string }],
      'view'
    >
    

    
    propose: TypedContractMethod<
      [_description: string, _metadataURI: string, _targetContract: AddressLike, _callData: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    quorumPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setProposalThreshold: TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setQuorum: TypedContractMethod<
      [_percent: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setStakingContract: TypedContractMethod<
      [_staking: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setVotingPeriod: TypedContractMethod<
      [_period: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    voteChoice: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    votingPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'castVote'): TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [AgentGovernance.ProposalStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProposalState'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVotingPower'): TypedContractMethod<
      [voter: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposalThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean, string, string] & {id: bigint, proposer: string, description: string, metadataURI: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, cancelled: boolean, callData: string, targetContract: string }],
      'view'
    >;
getFunction(nameOrSignature: 'propose'): TypedContractMethod<
      [_description: string, _metadataURI: string, _targetContract: AddressLike, _callData: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'quorumPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProposalThreshold'): TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuorum'): TypedContractMethod<
      [_percent: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStakingContract'): TypedContractMethod<
      [_staking: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVotingPeriod'): TypedContractMethod<
      [_period: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteChoice'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votingPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProposalCancelled'): TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
getEvent(key: 'QuorumUpdated'): TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
getEvent(key: 'ThresholdUpdated'): TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VotingPeriodUpdated'): TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProposalCancelled(uint256)': TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
      ProposalCancelled: TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
    

      'ProposalCreated(uint256,address,string,uint256,uint256)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    

      'QuorumUpdated(uint256)': TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
      QuorumUpdated: TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
    

      'ThresholdUpdated(uint256)': TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
      ThresholdUpdated: TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VotingPeriodUpdated(uint256)': TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;
      VotingPeriodUpdated: TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;
    
    };
  }