/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentEscrow {
      
    export type EscrowStruct = {payer: AddressLike, payee: AddressLike, amount: BigNumberish, conditionHash: BytesLike, timeout: BigNumberish, createdAt: BigNumberish, status: BigNumberish, memo: string}

    export type EscrowStructOutput = [payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, createdAt: bigint, status: bigint, memo: string] & {payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, createdAt: bigint, status: bigint, memo: string }
  
    }

  export interface AgentEscrowInterface extends Interface {
    getFunction(nameOrSignature: "createEscrow" | "disputeEscrow" | "escrows" | "getBalance" | "getEscrow" | "getPayeeEscrows" | "getPayerEscrows" | "nextEscrowId" | "owner" | "payeeEscrows" | "payerEscrows" | "refundAfterTimeout" | "rektToken" | "releaseEscrow" | "releasePartial" | "renounceOwnership" | "resolveDispute" | "totalCompleted" | "totalEscrowed" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowCreated" | "EscrowDisputed" | "EscrowRefunded" | "EscrowReleased" | "EscrowResolved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'disputeEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPayeeEscrows', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPayerEscrows', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextEscrowId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'payeeEscrows', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'payerEscrows', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundAfterTimeout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rektToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'releasePartial', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'totalCompleted', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEscrowed', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPayeeEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPayerEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEscrowId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payeeEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payerEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundAfterTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rektToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releasePartial', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCompleted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEscrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, payee: AddressLike, amount: BigNumberish, conditionHash: BytesLike, timeout: BigNumberish, memo: string];
      export type OutputTuple = [escrowId: bigint, payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, memo: string];
      export interface OutputObject {escrowId: bigint, payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowDisputedEvent {
      export type InputTuple = [escrowId: BigNumberish, disputer: AddressLike];
      export type OutputTuple = [escrowId: bigint, disputer: string];
      export interface OutputObject {escrowId: bigint, disputer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowRefundedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payer: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, payer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, payee: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payer: string, payee: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, payer: string, payee: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowResolvedEvent {
      export type InputTuple = [escrowId: BigNumberish, payToPayee: boolean, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payToPayee: boolean, amount: bigint];
      export interface OutputObject {escrowId: bigint, payToPayee: boolean, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentEscrow;
    waitForDeployment(): Promise<this>;

    interface: AgentEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEscrow: TypedContractMethod<
      [payee: AddressLike, amount: BigNumberish, conditionHash: BytesLike, timeout: BigNumberish, memo: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    disputeEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, bigint, bigint, string] & {payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, createdAt: bigint, status: bigint, memo: string }],
      'view'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [AgentEscrow.EscrowStructOutput],
      'view'
    >
    

    
    getPayeeEscrows: TypedContractMethod<
      [payee: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getPayerEscrows: TypedContractMethod<
      [payer: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    nextEscrowId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    payeeEscrows: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    payerEscrows: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    refundAfterTimeout: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rektToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releasePartial: TypedContractMethod<
      [escrowId: BigNumberish, releaseAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [escrowId: BigNumberish, payToPayee: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    totalCompleted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalEscrowed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [payee: AddressLike, amount: BigNumberish, conditionHash: BytesLike, timeout: BigNumberish, memo: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, bigint, bigint, string] & {payer: string, payee: string, amount: bigint, conditionHash: string, timeout: bigint, createdAt: bigint, status: bigint, memo: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [AgentEscrow.EscrowStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPayeeEscrows'): TypedContractMethod<
      [payee: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPayerEscrows'): TypedContractMethod<
      [payer: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextEscrowId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payeeEscrows'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'payerEscrows'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refundAfterTimeout'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rektToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releasePartial'): TypedContractMethod<
      [escrowId: BigNumberish, releaseAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [escrowId: BigNumberish, payToPayee: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalCompleted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEscrowed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowDisputed'): TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
getEvent(key: 'EscrowRefunded'): TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
getEvent(key: 'EscrowResolved'): TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'EscrowCreated(uint256,address,address,uint256,bytes32,uint256,string)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowDisputed(uint256,address)': TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
      EscrowDisputed: TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
    

      'EscrowRefunded(uint256,address,uint256)': TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
      EscrowRefunded: TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
    

      'EscrowReleased(uint256,address,address,uint256)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    

      'EscrowResolved(uint256,bool,uint256)': TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
      EscrowResolved: TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }