/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AgentEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentEscrow__factory>
getContractFactory(name: 'AgentGovernance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentGovernance__factory>
getContractFactory(name: 'AgentNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentNFT__factory>
getContractFactory(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentRegistry__factory>
getContractFactory(name: 'AgentStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentStaking__factory>
getContractFactory(name: 'ReputationOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReputationOracle__factory>
getContractFactory(name: 'TaskMarketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TaskMarketplace__factory>
getContractFactory(name: 'IAgentNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAgentNFT__factory>
getContractFactory(name: 'RewardDistributor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardDistributor__factory>
getContractFactory(name: 'REKTToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.REKTToken__factory>

  getContractAt(name: 'AgentEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentEscrow>
getContractAt(name: 'AgentGovernance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentGovernance>
getContractAt(name: 'AgentNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentNFT>
getContractAt(name: 'AgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentRegistry>
getContractAt(name: 'AgentStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentStaking>
getContractAt(name: 'ReputationOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReputationOracle>
getContractAt(name: 'TaskMarketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TaskMarketplace>
getContractAt(name: 'IAgentNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAgentNFT>
getContractAt(name: 'RewardDistributor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardDistributor>
getContractAt(name: 'REKTToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.REKTToken>

  deployContract(name: 'AgentEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentEscrow>
deployContract(name: 'AgentGovernance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentGovernance>
deployContract(name: 'AgentNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentNFT>
deployContract(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'AgentStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentStaking>
deployContract(name: 'ReputationOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationOracle>
deployContract(name: 'TaskMarketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TaskMarketplace>
deployContract(name: 'IAgentNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentNFT>
deployContract(name: 'RewardDistributor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardDistributor>
deployContract(name: 'REKTToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.REKTToken>

  deployContract(name: 'AgentEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentEscrow>
deployContract(name: 'AgentGovernance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentGovernance>
deployContract(name: 'AgentNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentNFT>
deployContract(name: 'AgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'AgentStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentStaking>
deployContract(name: 'ReputationOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationOracle>
deployContract(name: 'TaskMarketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TaskMarketplace>
deployContract(name: 'IAgentNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentNFT>
deployContract(name: 'RewardDistributor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardDistributor>
deployContract(name: 'REKTToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.REKTToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  