/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ReputationOracle {
      
    export type ReputationScoreStruct = {overall: BigNumberish, taskCompletion: BigNumberish, qualityScore: BigNumberish, reliability: BigNumberish, economicWeight: BigNumberish, tasksAttempted: BigNumberish, tasksSucceeded: BigNumberish, tasksOnTime: BigNumberish, lastUpdated: BigNumberish}

    export type ReputationScoreStructOutput = [overall: bigint, taskCompletion: bigint, qualityScore: bigint, reliability: bigint, economicWeight: bigint, tasksAttempted: bigint, tasksSucceeded: bigint, tasksOnTime: bigint, lastUpdated: bigint] & {overall: bigint, taskCompletion: bigint, qualityScore: bigint, reliability: bigint, economicWeight: bigint, tasksAttempted: bigint, tasksSucceeded: bigint, tasksOnTime: bigint, lastUpdated: bigint }
  
    }

  export interface ReputationOracleInterface extends Interface {
    getFunction(nameOrSignature: "TIER_GOLD" | "TIER_PLATINUM" | "TIER_SILVER" | "authorizeCaller" | "authorizedCallers" | "completionWeight" | "economicWeightBps" | "getOverallScore" | "getPeerRating" | "getReputation" | "getTier" | "getTierByScore" | "minimumTasksForReputation" | "owner" | "peerRatingCount" | "peerRatingSum" | "peerRatings" | "qualityWeight" | "recordTaskOutcome" | "reliabilityWeight" | "renounceOwnership" | "scores" | "setMinimumTasks" | "setWeights" | "submitPeerRating" | "transferOwnership" | "updatePeerRating"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CallerAuthorized" | "OwnershipTransferred" | "PeerRatingSubmitted" | "ReputationUpdated" | "WeightsUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'TIER_GOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIER_PLATINUM', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIER_SILVER', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizeCaller', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'authorizedCallers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'completionWeight', values?: undefined): string;
encodeFunctionData(functionFragment: 'economicWeightBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOverallScore', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPeerRating', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTierByScore', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'minimumTasksForReputation', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'peerRatingCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'peerRatingSum', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'peerRatings', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'qualityWeight', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordTaskOutcome', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reliabilityWeight', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'scores', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinimumTasks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWeights', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitPeerRating', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePeerRating', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'TIER_GOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIER_PLATINUM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIER_SILVER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedCallers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completionWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'economicWeightBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOverallScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPeerRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTierByScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumTasksForReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'peerRatingCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'peerRatingSum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'peerRatings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'qualityWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordTaskOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reliabilityWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scores', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinimumTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitPeerRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePeerRating', data: BytesLike): Result;
  }

  
    export namespace CallerAuthorizedEvent {
      export type InputTuple = [caller: AddressLike, authorized: boolean];
      export type OutputTuple = [caller: string, authorized: boolean];
      export interface OutputObject {caller: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PeerRatingSubmittedEvent {
      export type InputTuple = [ratee: AddressLike, rater: AddressLike, rating: BigNumberish];
      export type OutputTuple = [ratee: string, rater: string, rating: bigint];
      export interface OutputObject {ratee: string, rater: string, rating: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [agent: AddressLike, oldOverall: BigNumberish, newOverall: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, oldOverall: bigint, newOverall: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, oldOverall: bigint, newOverall: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WeightsUpdatedEvent {
      export type InputTuple = [completion: BigNumberish, quality: BigNumberish, reliability: BigNumberish, economic: BigNumberish];
      export type OutputTuple = [completion: bigint, quality: bigint, reliability: bigint, economic: bigint];
      export interface OutputObject {completion: bigint, quality: bigint, reliability: bigint, economic: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationOracle;
    waitForDeployment(): Promise<this>;

    interface: ReputationOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TIER_GOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TIER_PLATINUM: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TIER_SILVER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authorizeCaller: TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedCallers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    completionWeight: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    economicWeightBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getOverallScore: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getPeerRating: TypedContractMethod<
      [ratee: AddressLike, rater: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getReputation: TypedContractMethod<
      [agent: AddressLike, ],
      [ReputationOracle.ReputationScoreStructOutput],
      'view'
    >
    

    
    getTier: TypedContractMethod<
      [agent: AddressLike, ],
      [string],
      'view'
    >
    

    
    getTierByScore: TypedContractMethod<
      [score: BigNumberish, ],
      [string],
      'view'
    >
    

    
    minimumTasksForReputation: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    peerRatingCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    peerRatingSum: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    peerRatings: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    qualityWeight: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    recordTaskOutcome: TypedContractMethod<
      [agent: AddressLike, rewardAmount: BigNumberish, outcome: BigNumberish, qualityScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reliabilityWeight: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    scores: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {overall: bigint, taskCompletion: bigint, qualityScore: bigint, reliability: bigint, economicWeight: bigint, tasksAttempted: bigint, tasksSucceeded: bigint, tasksOnTime: bigint, lastUpdated: bigint }],
      'view'
    >
    

    
    setMinimumTasks: TypedContractMethod<
      [newMinimum: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWeights: TypedContractMethod<
      [_completion: BigNumberish, _quality: BigNumberish, _reliability: BigNumberish, _economic: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitPeerRating: TypedContractMethod<
      [ratee: AddressLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePeerRating: TypedContractMethod<
      [ratee: AddressLike, newRating: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TIER_GOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TIER_PLATINUM'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TIER_SILVER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorizeCaller'): TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedCallers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'completionWeight'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'economicWeightBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getOverallScore'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPeerRating'): TypedContractMethod<
      [ratee: AddressLike, rater: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [agent: AddressLike, ],
      [ReputationOracle.ReputationScoreStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTier'): TypedContractMethod<
      [agent: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTierByScore'): TypedContractMethod<
      [score: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'minimumTasksForReputation'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'peerRatingCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'peerRatingSum'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'peerRatings'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'qualityWeight'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordTaskOutcome'): TypedContractMethod<
      [agent: AddressLike, rewardAmount: BigNumberish, outcome: BigNumberish, qualityScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reliabilityWeight'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'scores'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {overall: bigint, taskCompletion: bigint, qualityScore: bigint, reliability: bigint, economicWeight: bigint, tasksAttempted: bigint, tasksSucceeded: bigint, tasksOnTime: bigint, lastUpdated: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setMinimumTasks'): TypedContractMethod<
      [newMinimum: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWeights'): TypedContractMethod<
      [_completion: BigNumberish, _quality: BigNumberish, _reliability: BigNumberish, _economic: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitPeerRating'): TypedContractMethod<
      [ratee: AddressLike, rating: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePeerRating'): TypedContractMethod<
      [ratee: AddressLike, newRating: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CallerAuthorized'): TypedContractEvent<CallerAuthorizedEvent.InputTuple, CallerAuthorizedEvent.OutputTuple, CallerAuthorizedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PeerRatingSubmitted'): TypedContractEvent<PeerRatingSubmittedEvent.InputTuple, PeerRatingSubmittedEvent.OutputTuple, PeerRatingSubmittedEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
getEvent(key: 'WeightsUpdated'): TypedContractEvent<WeightsUpdatedEvent.InputTuple, WeightsUpdatedEvent.OutputTuple, WeightsUpdatedEvent.OutputObject>;

    filters: {
      
      'CallerAuthorized(address,bool)': TypedContractEvent<CallerAuthorizedEvent.InputTuple, CallerAuthorizedEvent.OutputTuple, CallerAuthorizedEvent.OutputObject>;
      CallerAuthorized: TypedContractEvent<CallerAuthorizedEvent.InputTuple, CallerAuthorizedEvent.OutputTuple, CallerAuthorizedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PeerRatingSubmitted(address,address,uint256)': TypedContractEvent<PeerRatingSubmittedEvent.InputTuple, PeerRatingSubmittedEvent.OutputTuple, PeerRatingSubmittedEvent.OutputObject>;
      PeerRatingSubmitted: TypedContractEvent<PeerRatingSubmittedEvent.InputTuple, PeerRatingSubmittedEvent.OutputTuple, PeerRatingSubmittedEvent.OutputObject>;
    

      'ReputationUpdated(address,uint256,uint256,uint256)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    

      'WeightsUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<WeightsUpdatedEvent.InputTuple, WeightsUpdatedEvent.OutputTuple, WeightsUpdatedEvent.OutputObject>;
      WeightsUpdated: TypedContractEvent<WeightsUpdatedEvent.InputTuple, WeightsUpdatedEvent.OutputTuple, WeightsUpdatedEvent.OutputObject>;
    
    };
  }