/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TaskMarketplace {
      
    export type TaskApplicationStruct = {applicant: AddressLike, proposal: string, proposedReward: BigNumberish, appliedAt: BigNumberish}

    export type TaskApplicationStructOutput = [applicant: string, proposal: string, proposedReward: bigint, appliedAt: bigint] & {applicant: string, proposal: string, proposedReward: bigint, appliedAt: bigint }
  

    export type TaskStruct = {poster: AddressLike, worker: AddressLike, reward: BigNumberish, deadline: BigNumberish, createdAt: BigNumberish, completedAt: BigNumberish, taskType: BigNumberish, status: BigNumberish, taskDataURI: string, proofURI: string, conditionHash: BytesLike}

    export type TaskStructOutput = [poster: string, worker: string, reward: bigint, deadline: bigint, createdAt: bigint, completedAt: bigint, taskType: bigint, status: bigint, taskDataURI: string, proofURI: string, conditionHash: string] & {poster: string, worker: string, reward: bigint, deadline: bigint, createdAt: bigint, completedAt: bigint, taskType: bigint, status: bigint, taskDataURI: string, proofURI: string, conditionHash: string }
  
    }

  export interface TaskMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "applications" | "applyForTask" | "cancelTask" | "claimTask" | "disputeTask" | "expireTask" | "feeRecipient" | "getApplicationCount" | "getApplications" | "getPosterTasks" | "getTask" | "getWorkerTasks" | "nextTaskId" | "owner" | "platformFeeBps" | "postTask" | "posterTasks" | "rektToken" | "renounceOwnership" | "resolveDispute" | "setFeeRecipient" | "setPlatformFee" | "submitWork" | "tasks" | "totalTasksCreated" | "totalVolume" | "transferOwnership" | "verifyTask" | "workerTasks"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApplicationSubmitted" | "OwnershipTransferred" | "PlatformFeeUpdated" | "TaskCancelled" | "TaskClaimed" | "TaskCreated" | "TaskDisputed" | "TaskExpired" | "TaskVerified" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'applications', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'applyForTask', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'cancelTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimTask', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'disputeTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'expireTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApplicationCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApplications', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPosterTasks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getWorkerTasks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextTaskId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'postTask', values: [string, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'posterTasks', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rektToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalTasksCreated', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVolume', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyTask', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'workerTasks', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'applications', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyForTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expireTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApplicationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApplications', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPosterTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWorkerTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextTaskId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'posterTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rektToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTasksCreated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'workerTasks', data: BytesLike): Result;
  }

  
    export namespace ApplicationSubmittedEvent {
      export type InputTuple = [taskId: BigNumberish, applicant: AddressLike, proposal: string];
      export type OutputTuple = [taskId: bigint, applicant: string, proposal: string];
      export interface OutputObject {taskId: bigint, applicant: string, proposal: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCancelledEvent {
      export type InputTuple = [taskId: BigNumberish, poster: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, poster: string, timestamp: bigint];
      export interface OutputObject {taskId: bigint, poster: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskClaimedEvent {
      export type InputTuple = [taskId: BigNumberish, worker: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, worker: string, timestamp: bigint];
      export interface OutputObject {taskId: bigint, worker: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCreatedEvent {
      export type InputTuple = [taskId: BigNumberish, poster: AddressLike, reward: BigNumberish, taskType: BigNumberish, deadline: BigNumberish, taskDataURI: string];
      export type OutputTuple = [taskId: bigint, poster: string, reward: bigint, taskType: bigint, deadline: bigint, taskDataURI: string];
      export interface OutputObject {taskId: bigint, poster: string, reward: bigint, taskType: bigint, deadline: bigint, taskDataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskDisputedEvent {
      export type InputTuple = [taskId: BigNumberish, disputer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, disputer: string, timestamp: bigint];
      export interface OutputObject {taskId: bigint, disputer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskExpiredEvent {
      export type InputTuple = [taskId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, timestamp: bigint];
      export interface OutputObject {taskId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskVerifiedEvent {
      export type InputTuple = [taskId: BigNumberish, poster: AddressLike, worker: AddressLike, reward: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, poster: string, worker: string, reward: bigint, timestamp: bigint];
      export interface OutputObject {taskId: bigint, poster: string, worker: string, reward: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [taskId: BigNumberish, worker: AddressLike, proofURI: string, timestamp: BigNumberish];
      export type OutputTuple = [taskId: bigint, worker: string, proofURI: string, timestamp: bigint];
      export interface OutputObject {taskId: bigint, worker: string, proofURI: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskMarketplace;
    waitForDeployment(): Promise<this>;

    interface: TaskMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    applications: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint, bigint] & {applicant: string, proposal: string, proposedReward: bigint, appliedAt: bigint }],
      'view'
    >
    

    
    applyForTask: TypedContractMethod<
      [taskId: BigNumberish, proposal: string, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimTask: TypedContractMethod<
      [taskId: BigNumberish, worker: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    disputeTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    expireTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getApplicationCount: TypedContractMethod<
      [taskId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getApplications: TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskMarketplace.TaskApplicationStructOutput[]],
      'view'
    >
    

    
    getPosterTasks: TypedContractMethod<
      [poster: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskMarketplace.TaskStructOutput],
      'view'
    >
    

    
    getWorkerTasks: TypedContractMethod<
      [worker: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    nextTaskId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    postTask: TypedContractMethod<
      [taskDataURI: string, reward: BigNumberish, deadline: BigNumberish, taskType: BigNumberish, conditionHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    posterTasks: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    rektToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [taskId: BigNumberish, payWorker: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitWork: TypedContractMethod<
      [taskId: BigNumberish, proofURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, string, string, string] & {poster: string, worker: string, reward: bigint, deadline: bigint, createdAt: bigint, completedAt: bigint, taskType: bigint, status: bigint, taskDataURI: string, proofURI: string, conditionHash: string }],
      'view'
    >
    

    
    totalTasksCreated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalVolume: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyTask: TypedContractMethod<
      [taskId: BigNumberish, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    workerTasks: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'applications'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint, bigint] & {applicant: string, proposal: string, proposedReward: bigint, appliedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'applyForTask'): TypedContractMethod<
      [taskId: BigNumberish, proposal: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTask'): TypedContractMethod<
      [taskId: BigNumberish, worker: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'expireTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApplicationCount'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getApplications'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskMarketplace.TaskApplicationStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPosterTasks'): TypedContractMethod<
      [poster: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskMarketplace.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getWorkerTasks'): TypedContractMethod<
      [worker: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextTaskId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'postTask'): TypedContractMethod<
      [taskDataURI: string, reward: BigNumberish, deadline: BigNumberish, taskType: BigNumberish, conditionHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'posterTasks'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rektToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [taskId: BigNumberish, payWorker: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [taskId: BigNumberish, proofURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, string, string, string] & {poster: string, worker: string, reward: bigint, deadline: bigint, createdAt: bigint, completedAt: bigint, taskType: bigint, status: bigint, taskDataURI: string, proofURI: string, conditionHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'totalTasksCreated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalVolume'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyTask'): TypedContractMethod<
      [taskId: BigNumberish, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'workerTasks'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ApplicationSubmitted'): TypedContractEvent<ApplicationSubmittedEvent.InputTuple, ApplicationSubmittedEvent.OutputTuple, ApplicationSubmittedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'TaskCancelled'): TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
getEvent(key: 'TaskClaimed'): TypedContractEvent<TaskClaimedEvent.InputTuple, TaskClaimedEvent.OutputTuple, TaskClaimedEvent.OutputObject>;
getEvent(key: 'TaskCreated'): TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
getEvent(key: 'TaskDisputed'): TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
getEvent(key: 'TaskExpired'): TypedContractEvent<TaskExpiredEvent.InputTuple, TaskExpiredEvent.OutputTuple, TaskExpiredEvent.OutputObject>;
getEvent(key: 'TaskVerified'): TypedContractEvent<TaskVerifiedEvent.InputTuple, TaskVerifiedEvent.OutputTuple, TaskVerifiedEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'ApplicationSubmitted(uint256,address,string)': TypedContractEvent<ApplicationSubmittedEvent.InputTuple, ApplicationSubmittedEvent.OutputTuple, ApplicationSubmittedEvent.OutputObject>;
      ApplicationSubmitted: TypedContractEvent<ApplicationSubmittedEvent.InputTuple, ApplicationSubmittedEvent.OutputTuple, ApplicationSubmittedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint256,uint256)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'TaskCancelled(uint256,address,uint256)': TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
      TaskCancelled: TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
    

      'TaskClaimed(uint256,address,uint256)': TypedContractEvent<TaskClaimedEvent.InputTuple, TaskClaimedEvent.OutputTuple, TaskClaimedEvent.OutputObject>;
      TaskClaimed: TypedContractEvent<TaskClaimedEvent.InputTuple, TaskClaimedEvent.OutputTuple, TaskClaimedEvent.OutputObject>;
    

      'TaskCreated(uint256,address,uint256,uint8,uint256,string)': TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
      TaskCreated: TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
    

      'TaskDisputed(uint256,address,uint256)': TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
      TaskDisputed: TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
    

      'TaskExpired(uint256,uint256)': TypedContractEvent<TaskExpiredEvent.InputTuple, TaskExpiredEvent.OutputTuple, TaskExpiredEvent.OutputObject>;
      TaskExpired: TypedContractEvent<TaskExpiredEvent.InputTuple, TaskExpiredEvent.OutputTuple, TaskExpiredEvent.OutputObject>;
    

      'TaskVerified(uint256,address,address,uint256,uint256)': TypedContractEvent<TaskVerifiedEvent.InputTuple, TaskVerifiedEvent.OutputTuple, TaskVerifiedEvent.OutputObject>;
      TaskVerified: TypedContractEvent<TaskVerifiedEvent.InputTuple, TaskVerifiedEvent.OutputTuple, TaskVerifiedEvent.OutputObject>;
    

      'WorkSubmitted(uint256,address,string,uint256)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }