/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace RewardDistributor {
      
    export type AgentStruct = {wallet: AddressLike, reputation: BigNumberish, totalEarned: BigNumberish, pendingReward: BigNumberish, tasksCompleted: BigNumberish, registered: boolean}

    export type AgentStructOutput = [wallet: string, reputation: bigint, totalEarned: bigint, pendingReward: bigint, tasksCompleted: bigint, registered: boolean] & {wallet: string, reputation: bigint, totalEarned: bigint, pendingReward: bigint, tasksCompleted: bigint, registered: boolean }
  
    }

  export interface RewardDistributorInterface extends Interface {
    getFunction(nameOrSignature: "agentList" | "agentNFT" | "agents" | "baseRewardPerTask" | "claim" | "fundPool" | "getAgent" | "getAgentCount" | "getBalance" | "getPendingReward" | "owner" | "register" | "renounceOwnership" | "reportWork" | "rewardToken" | "setAgentNFT" | "setBaseReward" | "slash" | "totalDistributed" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentNFTSet" | "AgentRegistered" | "AgentSlashed" | "OwnershipTransferred" | "PoolFunded" | "RewardClaimed" | "WorkReported"): EventFragment;

    encodeFunctionData(functionFragment: 'agentList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agentNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'agents', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'baseRewardPerTask', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAgentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingReward', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'register', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reportWork', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAgentNFT', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setBaseReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'slash', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalDistributed', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'agentList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseRewardPerTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAgentNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDistributed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AgentNFTSetEvent {
      export type InputTuple = [nftContract: AddressLike];
      export type OutputTuple = [nftContract: string];
      export interface OutputObject {nftContract: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, timestamp: bigint];
      export interface OutputObject {agent: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentSlashedEvent {
      export type InputTuple = [agent: AddressLike, percent: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [agent: string, percent: bigint, newReputation: bigint];
      export interface OutputObject {agent: string, percent: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PoolFundedEvent {
      export type InputTuple = [funder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [funder: string, amount: bigint];
      export interface OutputObject {funder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkReportedEvent {
      export type InputTuple = [agent: AddressLike, score: BigNumberish, reward: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, score: bigint, reward: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, score: bigint, reward: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RewardDistributor extends BaseContract {
    
    connect(runner?: ContractRunner | null): RewardDistributor;
    waitForDeployment(): Promise<this>;

    interface: RewardDistributorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agentList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agentNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    agents: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, boolean] & {wallet: string, reputation: bigint, totalEarned: bigint, pendingReward: bigint, tasksCompleted: bigint, registered: boolean }],
      'view'
    >
    

    
    baseRewardPerTask: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    fundPool: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [wallet: AddressLike, ],
      [RewardDistributor.AgentStructOutput],
      'view'
    >
    

    
    getAgentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPendingReward: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    register: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reportWork: TypedContractMethod<
      [agent: AddressLike, score: BigNumberish, rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAgentNFT: TypedContractMethod<
      [_nftContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseReward: TypedContractMethod<
      [newBase: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    slash: TypedContractMethod<
      [agent: AddressLike, percent: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalDistributed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agentList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agentNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, boolean] & {wallet: string, reputation: bigint, totalEarned: bigint, pendingReward: bigint, tasksCompleted: bigint, registered: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'baseRewardPerTask'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundPool'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [wallet: AddressLike, ],
      [RewardDistributor.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingReward'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportWork'): TypedContractMethod<
      [agent: AddressLike, score: BigNumberish, rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAgentNFT'): TypedContractMethod<
      [_nftContract: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseReward'): TypedContractMethod<
      [newBase: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slash'): TypedContractMethod<
      [agent: AddressLike, percent: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDistributed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentNFTSet'): TypedContractEvent<AgentNFTSetEvent.InputTuple, AgentNFTSetEvent.OutputTuple, AgentNFTSetEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AgentSlashed'): TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PoolFunded'): TypedContractEvent<PoolFundedEvent.InputTuple, PoolFundedEvent.OutputTuple, PoolFundedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'WorkReported'): TypedContractEvent<WorkReportedEvent.InputTuple, WorkReportedEvent.OutputTuple, WorkReportedEvent.OutputObject>;

    filters: {
      
      'AgentNFTSet(address)': TypedContractEvent<AgentNFTSetEvent.InputTuple, AgentNFTSetEvent.OutputTuple, AgentNFTSetEvent.OutputObject>;
      AgentNFTSet: TypedContractEvent<AgentNFTSetEvent.InputTuple, AgentNFTSetEvent.OutputTuple, AgentNFTSetEvent.OutputObject>;
    

      'AgentRegistered(address,uint256)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AgentSlashed(address,uint256,uint256)': TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
      AgentSlashed: TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PoolFunded(address,uint256)': TypedContractEvent<PoolFundedEvent.InputTuple, PoolFundedEvent.OutputTuple, PoolFundedEvent.OutputObject>;
      PoolFunded: TypedContractEvent<PoolFundedEvent.InputTuple, PoolFundedEvent.OutputTuple, PoolFundedEvent.OutputObject>;
    

      'RewardClaimed(address,uint256,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'WorkReported(address,uint256,uint256,uint256)': TypedContractEvent<WorkReportedEvent.InputTuple, WorkReportedEvent.OutputTuple, WorkReportedEvent.OutputObject>;
      WorkReported: TypedContractEvent<WorkReportedEvent.InputTuple, WorkReportedEvent.OutputTuple, WorkReportedEvent.OutputObject>;
    
    };
  }