/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAgentNFT, IAgentNFTInterface } from "../../RewardDistributor.sol/IAgentNFT.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "getTokenId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "isActive",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IAgentNFT__factory {
    static readonly abi = _abi;
    static createInterface(): IAgentNFTInterface {
      return new Interface(_abi) as IAgentNFTInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAgentNFT {
      return new Contract(address, _abi, runner) as unknown as IAgentNFT;
    }
  }
  